theme = "levi"

[editor]
bufferline = "always"
line-number = "relative"

# This is convenient for finding neighbouring files in deeply nested
# directories
[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

# Open lazygit in a popup
[keys.normal]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
