[[language]]
name = "vue"
language-servers = ["typescript-language-server", "eslint"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

 [language-server.eslint.config]
 format = true
 nodePath = ""
 onIgnoredFiles = "off"
 packageManager = "yarn"
 quiet = false
 rulesCustomizations = []
 run = "onType"
 useESLintClass = false
 validate = "on"
 codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
 codeActionOnSave = { mode = "all" }
 experimental = { }
 problems = { shortenToSingleLine = false }
 workingDirectory = { mode = "auto" }

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/Users/lececcato/.nvm/versions/node/v21.6.2/lib/node_modules/@vue/typescript-plugin"
languages = ["vue"]
