[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { enable = true, mode = "fixAll" }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"
config.plugins = [
  { name = "@vue/typescript-plugin", location = "/Users/lececcato/.nvm/versions/node/v21.6.2/lib/node_modules/@vue/typescript-plugin", languages = ["javascript", "typescript", "vue"] }
]

[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]
config.hostInfo = "helix"
# config.typescript = { tsdk = "/Users/lececcato/.nvm/versions/node/v21.6.2/lib/node_modules/typescript/lib" }

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server", "eslint"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint"]
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
auto-format = true

[[language]]
name = "vue"
auto-format = true
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
language-servers = ["vue-language-server", "eslint"]
roots = ["package.json", "vue.config.js", "tsconfig.json"]
